version: "3.8"
services:
  web:
    build: .
    container_name: main-dashboard
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  jupyter:
    image: "jupyter/base-notebook"
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/code
    environment:
      - JUPYTER_TOKEN=easy
  rstudio:
    image: "rocker/rstudio"
    container_name: rstudio
    ports:
      - "8787:8787"
    environment:
      - DISABLE_AUTH=true
  wetty:
    image: amcgaw07/wettygit:firsttry
    container_name: git-bash
    ports:
      - "3000:3000"
    volumes:
      - .:/code
  markdown:
    image: "v4tech/markdown-editor"
    container_name: markdown
    ports:
      - "12345:80"
  sonarqube:
    image: "sonarqube:latest"
    container_name: sonar-qube
    ports:
      - "9001:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - sonarqube
  tensorflow:
    image: "tensorflow/tensorflow:nightly-jupyter"
    container_name: tensorflow
    ports:
      - "8889:8888"
    environment:
      - JUPYTER_TOKEN=easy
  sonarscan:
    image: "newtmitch/sonar-scanner"
    restart: on-failure
    volumes:
      - ./sample:/usr/src
    networks:
      - sonarqube
  vscode:
    image: ghcr.io/linuxserver/code-server
    container_name: visual-studio
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
  orange:
    image: acopar/orange-docker

    ports: 
      - "127.0.0.1:5901:5901"
      - "127.0.0.1:6901:6901"
    volumes:
      - ./orange-profile:/home/orange/.config/biolab.si

volumes:
    orange-profile:
  
networks:
  sonarqube: