version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  jupyter:
    image: "jupyter/base-notebook"
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=easy
  rstudio:
    image: "rocker/rstudio"
    ports:
      - "8787:8787"
    environment:
      - DISABLE_AUTH=true
  wetty:
    image: amcgaw07/wettygit:firsttry
    ports:
      - "3000:3000"
    volumes:
      - .:/code
  markdown:
    image: "v4tech/markdown-editor"
    ports:
      - "12345:80"
  sonarqube:
    image: "sonarqube:latest"
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  tensorflow:
    image: "tensorflow/tensorflow:nightly-jupyter"
    ports:
      - "8889:8888"
    environment:
      - JUPYTER_TOKEN=easy
  sonarscan:
    image: "newtmitch/sonar-scanner"
    volumes:
      - .:/code/example
    links:
      - "sonarqube"